# Generated by Django 3.0.4 on 2020-03-15 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=6)),
                ('summary', models.TextField(default='')),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 5, 52, 24, 163101, tzinfo=utc))),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='MinorUpdateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateTitle', models.CharField(default='아직 추가 패치 노트 없음', max_length=255)),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 5, 52, 24, 165107, tzinfo=utc))),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.VersionModel')),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='MinorUpdateItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('item', models.TextField()),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 5, 52, 24, 169118, tzinfo=utc))),
                ('minorUpdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.MinorUpdateModel')),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 5, 52, 24, 164104, tzinfo=utc))),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.VersionModel')),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='ChampionPatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(default='', max_length=255)),
                ('contentHtml', models.TextField(default='')),
                ('championSummaryText', models.TextField(default='')),
                ('championQuoteText', models.TextField(default='')),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 5, 52, 24, 170120, tzinfo=utc))),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.VersionModel')),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='ChampionMinorPatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(default='', max_length=255)),
                ('contentHtmlList', models.TextField(default='')),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 5, 52, 24, 171123, tzinfo=utc))),
                ('minorUpdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.MinorUpdateModel')),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentHtml', models.TextField()),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 5, 52, 24, 165107, tzinfo=utc))),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.HeaderModel')),
            ],
            options={
                'ordering': ['-updateDate'],
            },
        ),
    ]
