# Generated by Django 3.0.4 on 2020-03-14 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestChampionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField()),
                ('summary', models.TextField()),
                ('header', models.CharField(max_length=255)),
                ('article', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VersionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=6)),
                ('summary', models.TextField(default='')),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2020, 3, 14, 5, 41, 44, 525096, tzinfo=utc))),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='MinorUpdateModel',
            fields=[
                ('updateTitle', models.CharField(default='아직 추가 패치 노트 없음', max_length=255, primary_key=True, serialize=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='updates.VersionModel')),
            ],
        ),
        migrations.CreateModel(
            name='MinorUpdateItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('item', models.TextField()),
                ('minorUpdate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='updates.MinorUpdateModel')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='updates.VersionModel')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionPatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(default='', max_length=255)),
                ('contentHtml', models.TextField(default='')),
                ('championSummaryText', models.TextField(default='')),
                ('championQuoteText', models.TextField(default='')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='updates.VersionModel')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionMinorPatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(default='', max_length=255)),
                ('contentHtmlList', models.TextField(default='')),
                ('minorUpdate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='updates.MinorUpdateModel')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentHtml', models.TextField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='updates.HeaderModel')),
            ],
        ),
    ]
